# Basic provisioning example
- name: Ansible test
hosts: localhost
tasks:
- name: launching AWS instance using Ansible
ec2:
key_name: aws_instance_Ansible
instance_type: t2.micro
image: ami-0ba1c3ef9156479a2
region: eu-west-1
wait: yes
group: Ansible
count: 1
vpc_subnet_id: BRTN
assign_public_ip: yes
aws_access_key: AKIAZOLZZAJW7VCXERMY
Aws_secret_key: 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
